language: generic

os: osx
osx_image: xcode6.4

sudo: false

env:

  matrix:
    - CONDA_PY=36

  global:
    - FENICS_VERSION="2017.2.dev"
    # travis encrypt BINSTAR_TOKEN="..." --repo mikaem/Oasis
    - secure: "ibotzq1hr1KOEdE3lgArJ+Wq2donqzT78fZ0mnUQC0fsAh0E74LerxmwALouZtn0d58fm9kfTgHdz26GOOcaALL8joSvNM5ut/3EC0uPuXh7/GTLGWPdMq0prTqZDij2kedUuWkBY7FbnDoGYFby/IdXJOubdDvcEqTqeTBn2efCjYEmL0tbjjJEbU0s4BXLb8Dt5J0U/LcqIdpfggDN3IO0OLSaGhjpGAxt9A9epNicdiRMjNCcAJmi36YGVwlEHBagUPIAfq6KdTHcBhynJSkmjtOFEtWIVeplQ5dku0zomZau1dsn819IyXwq0zCrcwF0565uY288hm2LgDMvEHhK3NkF9o87fzLu6NBV99bjVBlCmWASCUZckQquUcQKlsfjjkFHrZyWw8PNn6+VXTKNz46M/g8bSHrYcnv6SdtLWEwUFycN7XD+xDbMEJWHptR6GAYRfeV8/8WMjimaffGuhY38vhhFzqRo/h0QIpWh/vSKMKwGRS1V/8iAhDnUfMDobs47JkFTIruFc+xHFfpebFD1w6/mJeLh42lz/JQzi1RkDbzfK7wS9uInJUjhcmDYi2wS2EQ/7p1cNngXdDKf+Ml7iIMcSsUJRFH0xRrNNiBOfW3rE4vmTL3b+PHm43KvSWCQDaM/rhMNW7XyeeIhw1q/5LVPblFaNZUTMlY="

before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew

install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --set always_yes yes
      conda config --set show_channel_urls true
      conda config --add channels conda-forge
      conda config --add channels mikaem/label/OSX-10.12-clang
      conda update -q conda
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup
      conda install --yes fenics=${FENICS_VERSION} pytest
      #export INSTANT_CACHE_DIR="/Users/travis/miniconda2/.cache/instant"

after_failure:
    - find /Users/travis/miniconda2/.cache/instant/error/* -name 'compile.log' -print -exec cat '{}' \;

script:
    - export INSTANT_CACHE_DIR="${HOME}/instant"
    - mpirun -np 1 python NSfracStep.py problem=TaylorGreen2D T=0.01 Nx=50 Ny=50
    - cd ${PWD}/tests
    - python test_NSfracStep.py
    - python test_NSCoupled.py
